### ISSUE TITLE
Provide ability to specify backend URL

### ISSUE THREAD

**Issue by tadq** [dustinblackman/oatmeal#11]
Is there a way to provide backend Ollama URL?
Instead of current default of http://localhost:11434

**Comment by tadq** [comment]
Hi, I am running Ollama on few local servers. CORS is enabled.

**Comment by dustinblackman** [comment]
Nice! That's fun.
Fixed in [v0.7.0](https://github.com/dustinblackman/oatmeal/releases/tag/v0.7.0). Thanks!

**Comment by tadq** [comment]
Love it. Works well.
Thanks a lot.
