### ISSUE TITLE
Add more documentation on how to get sidecar approach working for neovim

### ISSUE THREAD

**Issue by StevenBucher98** [dustinblackman/oatmeal#13]
Hi! Love this project and been playing around with the basic prompting experience and been having trouble recreating the GIF from this blog post where I found this project https://dustinblackman.com/posts/oatmeal/

Any tips on how to get this working? I tried `oatmeal --editor neovim` but get error that neovim is not running.

**Comment by dustinblackman** [comment]
The neovim extension is doing all the heavy lifting for that. :) https://github.com/dustinblackman/oatmeal.nvim

**Comment by dustinblackman** [comment]
@StevenBucher98 Did the extension work for you?

**Comment by StevenBucher98** [comment]
It did eventually, it took me a while cause I am unfamiliar with lazy vim 😄 I created these rough implementation instructions:



a.	install oatmeal: 
https://github.com/dustinblackman/oatmeal
brew install dustinblackman/tap/oatmeal

b.	Install ollama2:
brew install dustinblackman/tap/oatmeal
https://ollama.ai/download/Ollama-darwin.zip

c.	install neovim
https://github.com/neovim/neovim

d.	Install lazy.vim
https://github.com/folke/lazy.nvim
https://www.lazyvim.org/installation

e.	In .config/nvim/lua/plugins create a new file named 'oatmeal.lua"

f.	Add this code:
return
{
  {
    "dustinblackman/oatmeal.nvim",
    cmd = { "Oatmeal" },
    keys = {
        { "<leader>om", mode = "n", desc = "Start Oatmeal session" },
    },
    opts = {
        backend = "ollama",
        model = "llama2:latest",
    },
  },
}

**Comment by dustinblackman** [comment]
Nice good stuff! What were you previously using as a package manager? Lazy.nvim is not a requirement, just an option to install it.

**Comment by StevenBucher98** [comment]
I've been using brew as package manager, Lazy.nvim is not? It seemed like a requirement for the side car/side by side experience with nvim

**Comment by dustinblackman** [comment]
Sorry I meant plugin manager. Lazy.nvim is just one way to manage plugins in Neovim.

**Comment by StevenBucher98** [comment]
I used lazy vim for the plugin management, I manually input all the lua files to get it working

**Comment by dustinblackman** [comment]
Ah! Understood, you were doing it by hand.

I'm glad you got everything working! I don't feel like Oatmeal should be documenting how to do a full setup of Neovim+Ollama, as this is just the UI. I'll leave it to each repositories documentation for setup.
