### ISSUE TITLE
Issues with connections

### ISSUE THREAD

**Issue by tadq** [dustinblackman/oatmeal#19]
Since I am using ollama over network connections from time to time I get start up error message that server is not available.
But server was just slow to respond or had temporary network issue. 

Does oatmeal try few times to reconnect? It would be nice if it would retry at least few times before giving up.

**Comment by dustinblackman** [comment]
Fixed in [v0.8.0](https://github.com/dustinblackman/oatmeal/releases/tag/v0.8.0). Thanks!
