### ISSUE TITLE
Error interacting with clipboard, Display parsing error

### ISSUE THREAD

**Issue by fr-str** [dustinblackman/oatmeal#21]
i'm on windows connected to my other pc thru ssh on [windows terminal](https://github.com/microsoft/terminal), i tried running it in tmux and outside same result

i also tried building from source, didn't help

Question: does the host system need GUI for this to work?

```
$ RUST_BACKTRACE=1 ./oatmeal --editor neovim --backend ollama --model codellama:latest
Oh no! Oatmeal has failed with the following app version and error.

Version: 0.8.2
Commit: 4cd207a
Error: Unknown error while interacting with the clipboard: Display parsing error

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>

```

**Comment by dustinblackman** [comment]
This is fixed in [v0.9.0](https://github.com/dustinblackman/oatmeal/releases/tag/v0.9.0). Thanks!
