### ISSUE TITLE
Terminated by SIGKILL

### ISSUE THREAD

**Issue by kapral18** [dustinblackman/oatmeal#23]
![CleanShot 2023-12-14 at 12 48 20](https://github.com/dustinblackman/oatmeal/assets/1625373/0dcd6e64-6682-4c5d-9912-7e7455f0ae31)

MacOS 14.1.2, M1 Max

Update:

Only happens when `brew install`. With `cargo install` works fine

**Comment by dustinblackman** [comment]
That's weird... The only thing I can see that caused that was my change to [dtolnay's github actions](https://github.com/dustinblackman/oatmeal/commit/124df90513e029902384caaeae515fdb789aee46) as actions-rs is dead. I'll revert and retry.

**Comment by dustinblackman** [comment]
Fixed in v0.9.1. Thanks!
