### ISSUE TITLE
option to disable auto scrolling on output

### ISSUE THREAD

**Issue by joseluis** [dustinblackman/oatmeal#26]
It'd be nice to have the option to disable scrolling on output, similar to how it can be configured in most terminals, so that's possible to scroll back and forth while it's working on the answer.

**Comment by dustinblackman** [comment]
Sure that's a good idea! You'd imagine it as a flag such as `--auto-scroll false`?

**Comment by joseluis** [comment]
I miss to be able to change the app options using commands from inside the running app, and/or via a user config file, but if those options are not currently possible I guess a flag would be the next bext thing. I don't like to set env variables to configure programs options but maybe that's just me.

**Comment by dustinblackman** [comment]
Fixed in v0.11.0 with https://github.com/dustinblackman/oatmeal/commit/8b753526033dfd540e82098dd84847816054f314. Thanks!
