### ISSUE TITLE
Clipboard error on Wayland

### ISSUE THREAD

**Issue by ThatOneCalculator** [dustinblackman/oatmeal#28]
Upon running `oatmeal` from the CLI, I get `Whoops, it looks like the editor clipboard isn't setup properly...`. My system clipboard provider is `wl-copy` (the default on most Wayland environments).

**Comment by dustinblackman** [comment]
Looks related to https://github.com/1Password/arboard/issues/114, which is what I'm using for clipboard management. 

The clipboard service isn't mandatory since 0.9.0, so Oatmeal should still be usable without it by running `oatmeal --editor none`. Does that work?

**Comment by ThatOneCalculator** [comment]
The app loads, but just shows the error without the flag passed. Klipper isn't related to wl-copy.

**Comment by dustinblackman** [comment]
Understood! I believe I see the solution, I'll push it out in the next version.

**Comment by dustinblackman** [comment]
Fixed in v0.10.0. Thanks!
