### ISSUE TITLE
Multiline line prompt

### ISSUE THREAD

**Issue by jim-at-jibba** [dustinblackman/oatmeal#43]
I have a feeling this is a really silly question but I cant figure out how to do multi line prompts. I want to press enter to go to the next line but it just submits the prompt. I have tried various other ways but all submit.

Thanks

**Comment by dustinblackman** [comment]
Hey there!

This is a dup of https://github.com/dustinblackman/oatmeal/issues/16. I’ve attempted implementing a rough version of it myself, but it ends up being pretty complex. 

Gonna close this one, we can continue in the other issue. Thanks!
