### ISSUE TITLE
Add common environment variables

### ISSUE THREAD

**Issue by dustinblackman** [dustinblackman/oatmeal#8]
## Overview

Following up on https://github.com/dustinblackman/oatmeal/pull/6, add common environment variables shared across other apps for OpenAI such as:

- OPENAI_MODEL
- OPENAI_API_KEY
- OPENAI_KEY

**Comment by suhr** [comment]
It would be nice to support `OLLAMA_URL` as well.

**Comment by dustinblackman** [comment]
While I see the appeal of this, Oatmeal's environment variable configs are tied to clap, which only allows one environment variable. Decoupling that and having to mange several variants of envs sounds tedious. The following I'd say is good enough.

```bash
export OPENAI_KEY=keysecretkey
export OATMEAL_OPENAI_TOKEN=$OPENAI_KEY
```

Marking as wont fix.
